[package]
name = "app"
version = "1.0.0"
description = "万遥客户端 - 一个现代化的客户端应用程序"
authors = ["Wanyao Team"]
license = "MIT"
repository = "https://github.com/goddeath23333/wanyao-client.git"
homepage = "https://github.com/goddeath23333/wanyao-client#readme"
edition = "2021"
rust-version = "1.90.0"
default-run = "app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.1", features = ["protocol-asset"] }
tauri-plugin-log = "2.7.1"
sysinfo = "0.31"
wmi = "0.13"
winreg = "0.50"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
